// <auto-generated />
using System;
using ApiExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiExample.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20231206002229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("ApiExample.Classes.CharacterBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanFly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeightInInches")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEvil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CharacterBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ApiExample.Models.Hero", b =>
                {
                    b.HasBaseType("ApiExample.Classes.CharacterBase");

                    b.HasDiscriminator().HasValue("Hero");
                });

            modelBuilder.Entity("ApiExample.Models.Villain", b =>
                {
                    b.HasBaseType("ApiExample.Classes.CharacterBase");

                    b.HasDiscriminator().HasValue("Villain");
                });
#pragma warning restore 612, 618
        }
    }
}
